### ISSUE TITLE
 RNCollapsingToolbarPackage is not abstract and does not override abstract method createJSModules() in ReactPackage

### ISSUE THREAD

**Issue by john1jan** [cesardeazevedo/react-native-collapsing-toolbar#7]
error: RNCollapsingToolbarPackage is not abstract and does not override abstract method createJSModules() in ReactPackage

Getting this error when I tried to build

**Comment by cesardeazevedo** [comment]
Hi, which react-native version are you using?

**Comment by pwob** [comment]
Hi I am encountering this error, my react-native version is 0.46.

**Comment by cesardeazevedo** [comment]
The latest version won't work with react-native version 0.46, since there is compatibility changes in the past, [see](https://github.com/cesardeazevedo/react-native-collapsing-toolbar/commit/0b0f5fbf50704407f59de87e07b363a792fd8c25)

Using `1.0.0-beta.4` may work, but i recommend you take some time to upgrade react-native instead.

**Comment by schatzdesigns** [comment]
Try removing the @Override Interface on the method, it should work. I think there are compatibility changes with the update.
